name: provide_this
description: >-
  A set of mixins with methods to conveniently
  build a Provider on any class or Widget.
version: 0.1.0
homepage: https://github.com/james-alex/provide_this

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
